name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4

      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Collect tests
        id: collect-tests
        run: echo "tests=$(nix develop --command pytest --collect-only -q | head -n -1 | jq -R -s -c 'split("\n") | map(select(length > 0))')" >> $GITHUB_OUTPUT

    outputs:
      tests: ${{ steps.collect-tests.outputs.tests }}

  parallel_tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJson(needs.build.outputs.tests) }}

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4

      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Run tests
        run: nix develop --command pytest ${{ matrix.test }} -vv
