name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Collect tests
        id: collect-tests
        run: |
          tests=$(nix develop --accept-flake-config --command pytest --collect-only -q | awk -F'::' '/::/{split($3, a, "\\["); print "\""$1"::"$2"::"a[1]"\""}' | sort | uniq | paste -sd "," - | sed 's/^/[/;s/$/]/')
          echo "tests=$tests" >> $GITHUB_OUTPUT

    outputs:
      tests: ${{ steps.collect-tests.outputs.tests }}

  test:
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJson(needs.build.outputs.tests) }}

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: nix develop --accept-flake-config --command pytest -n 5 ${{ matrix.test }} -vv
