name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      #      - name: Use Nix Shell
      #        uses: rrbutani/use-nix-shell-action@v1
      #        with:
      #          extraNixOptions: --accept-flake-config
      #
      #      - name: Collect tests
      #        id: collect-tests
      #        run: echo "TESTS=$(pytest --collect-only -q | jq -R -s -c 'split("\n") | map(select(length > 0))')" >> $GITHUB_OUTPUT

      - name: Collect tests
        id: collect-tests
        run: echo 'tests=["tests/cli/test_cli.py::TestCli::test_rebuild[dry-build-outputs0]","tests/cli/test_cli.py::TestCli::test_rebuild[build-outputs1]","tests/cli/test_cli.py::TestCli::test_rebuild[test-outputs2]","tests/cli/test_cli.py::TestCli::test_rebuild[switch-outputs3]","tests/cli/test_cli.py::TestCli::test_newhost","tests/cli/test_cli.py::TestCli::test_init_newhost","tests/cli/test_cli.py::TestCli::test_update[inputs=[]]","tests/cli/test_cli.py::TestCli::test_update[inputs=['nixpkgs']]","tests/cli/test_cli.py::TestCli::test_update[inputs=['nixpkgs', 'nixos']]","tests/cli/test_cli.py::TestCli::test_update[inputs=['nixpkgs', 'agenix']]","tests/unit/test_gitrepo.py::TestGitRepo::test_add[]","tests/unit/test_secrets.py::TestSecrets::test_in_repo[]","tests/unit/test_secrets.py::TestSecrets::test_init","tests/unit/test_secrets.py::TestSecrets::test__add","14 tests collected in 0.02s"]' >> $GITHUB_OUTPUT

    outputs:
      tests: ${{ steps.collect-tests.outputs.tests }}

  parallel_tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJson(needs.build.outputs.tests) }}

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: pytest ${{ matrix.test }} -vv
