name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Use Nix Shell
        uses: rrbutani/use-nix-shell-action@v1
        with:
          extraNixOptions: --accept-flake-config

      - name: Collect tests
        id: collect-tests
        run: echo "tests=$(pytest --collect-only -q | head -n -1 | jq -R -s -c 'split("\n") | map(select(length > 0))')" >> $GITHUB_OUTPUT

    outputs:
      tests: ${{ steps.collect-tests.outputs.tests }}

  parallel_tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJson(needs.build.outputs.tests) }}

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Nix Shell
        uses: rrbutani/use-nix-shell-action@v1
        with:
          extraNixOptions: --accept-flake-config

      - name: Run tests
        run: pytest ${{ matrix.test }} -vv
